version: '3.6'

services:
  server:
    build: .
    ports:
      - '3004:3004'
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'jobqueue'